name: Assign to Project Board

on:

  issues:
    types: [opened, edited]
  pull_request:
     types: [opend, edited]


jobs:
  assign-to-board:
    runs-on: ubuntu-latest

    steps: 
      - name: Assign to Project Board
        uses: action/github-script@v4
        with:
          script: |
            const uses: actions/github.contex.payload.issue || github.context.payload.pull_request;
            const projectNumber = '123': // Replace with your project board number
            const octokit = new github.Github.GitHub(token);


            await octokit.projects.createCard({
              column_id: projectNumber,
              content_id: issue.id,
              content_type: 'Issue'
            });
